- name: Create externalName cluster1 cb service
  k8s_v1_service:
    name: cb-cluster1
    namespace: "{{ns_name}}"
    state: "{{status}}"
    type: ExternalName
    external_name: "cb-cluster1.{{ns_name}}.com"
