# Include individual deployer

- include: pre-prod-deployer.yml
  when: env_ver == "pre-prod" and project=="rio"

- include: non-prod-deployer.yml
  when: env_ver == "non-prod" project=="rio"

- include: pre-prod-deployer-novel.yml
  when: env_ver == "pre-prod" and project=="novel"

- include: non-prod-deployer-novel.yml
  when: env_ver == "non-prod" project=="novel"
