---

# Include variable and secrets based on type of environment
# all is available across
- include_vars: ../../group_vars/all
  no_log: true
  when: env_ver == "non-prod"

- include_vars: ../../group_vars/nonprod.yml
  no_log: true
  when: env_ver == "non-prod"


# Feature teams
- name: Generate git2consul deployment template
  template: >
     src="{{ role_path }}/files/non-prod/git2consul.j2"
     dest=/tmp/git2consul.yml
  when: status == "present" and project == "rio"

- name: Install git2consul
  shell: kubectl apply -f "/tmp/git2consul.yml" --namespace "mongo-consul"
  when: status == "present" and project == "rio"
  tags: git2consul

# Feature teams
- name: Generate git2consul deployment template
  template: >
     src="{{ role_path }}/files/novel-np/git2consul.j2"
     dest=/tmp/git2consul.yml
  when: status == "present" and project == "novel"

- name: Install git2consul
  shell: kubectl apply -f "/tmp/git2consul.yml" --namespace "mongo-consul"
  when: status == "present" and project == "rio"
  tags: git2consul

#Remove incase state is absent
- name: Delete git2consul
  shell: kubectl delete pods,services,deploy -l app=kong --namespace "{{ns_name}}"
  when: status == "absent"
