# domain for internal/feature teams
domain: "mongo-poc.com"
# Consul
# Specify this for consul prefix start path
conf_start_path: application-config
# Couchbase type
# Int & QA are simple and rest mds
couchbase_type: vm_simple
#couchbase_type: vm_simple
couchbase_version: 5
##################################################
# Instance group preprod namespaces.
machineType: m4.4xlarge
maxSize: 15
minSize: 10
##################################################

##################################################
##################################################
# Couchbase VM values for pre-prod environments.
# Assuming this to be in us-west-2.

# Pre-prod Details
key_name: couchbase-uat-oregon
vpc_cidr: 172.20.0.0/16
db_subnets: "subnet-d2d9e29a,subnet-908e96f6,subnet-4226ee18"
vpc_id: vpc-118a2f68
vpc_region: us-west-2

#################################################

##################################################
# VPC details
# Quota - allocation - For feature team ns.
# Needs to be changed for UAT/STAGE/QA/INT
kube_pvc_quota: "{{pvc_quota}}"
kube_secret_quota: "{{secret_quota}}"
kube_cpu_quota: "{{cpu_quota}}"
kube_ram_quota: "{{ram_quota}}"

###################################################
# Helm download repos:
helm_url: https://storage.googleapis.com/kubernetes-helm/helm-v2.7.1-linux-amd64.tar.gz
helm_folder: /usr/local/bin

###################################################
# ACM Certificates - These match with namespace name. For feature teams, we can use *certs.
# @TODO
# Include certs based on ns. Used for pre-prod. Using *.mongo-poc.com for now
mongo_certs: arn:aws:acm:us-west-2:95951367244:certificate/b1b927af-d4d4-4006-9f8f-0381e51fb033
